const countries = [
  { id: 1, label: 'Afghanistan' },
  { id: 2, label: 'Albania' },
  { id: 3, label: 'Algeria' },
  { id: 4, label: 'Andorra' },
  { id: 5, label: 'Angola' },
  { id: 6, label: 'Antigua and Barbuda' },
  { id: 7, label: 'Argentina' },
  { id: 8, label: 'Armenia' },
  { id: 9, label: 'Australia' },
  { id: 10, label: 'Austria' },
  { id: 11, label: 'Azerbaijan' },
  { id: 12, label: 'Bahamas' },
  { id: 13, label: 'Bahrain' },
  { id: 14, label: 'Bangladesh' },
  { id: 15, label: 'Barbados' },
  { id: 16, label: 'Belarus' },
  { id: 17, label: 'Belgium' },
  { id: 18, label: 'Belize' },
  { id: 19, label: 'Benin' },
  { id: 20, label: 'Bhutan' },
  { id: 21, label: 'Bolivia, Plurinational State of' },
  { id: 22, label: 'Bosnia and Herzegovina' },
  { id: 23, label: 'Botswana' },
  { id: 24, label: 'Brazil' },
  { id: 25, label: 'Brunei Darussalam' },
  { id: 26, label: 'Bulgaria' },
  { id: 27, label: 'Burkina Faso' },
  { id: 28, label: 'Burundi' },
  { id: 29, label: 'Cambodia' },
  { id: 30, label: 'Cameroon' },
  { id: 31, label: 'Canada' },
  { id: 32, label: 'Cape Verde' },
  { id: 33, label: 'Central African Republic' },
  { id: 34, label: 'Chad' },
  { id: 35, label: 'Chile' },
  { id: 36, label: 'China' },
  { id: 37, label: 'Colombia' },
  { id: 38, label: 'Comoros' },
  { id: 39, label: 'Congo' },
  { id: 40, label: 'Congo, Democratic Republic of the' },
  { id: 41, label: 'Cook Islands' },
  { id: 42, label: 'Costa Rica' },
  { id: 43, label: 'Côte d\'Ivoire' },
  { id: 44, label: 'Croatia' },
  { id: 45, label: 'Cuba' },
  { id: 46, label: 'Curaçao' },
  { id: 47, label: 'Cyprus' },
  { id: 48, label: 'Czech Republic' },
  { id: 49, label: 'Denmark' },
  { id: 50, label: 'Djibouti' },
  { id: 51, label: 'Dominica' },
  { id: 52, label: 'Dominican Republic' },
  { id: 53, label: 'Ecuador' },
  { id: 54, label: 'Egypt' },
  { id: 55, label: 'El Salvador' },
  { id: 56, label: 'Equatorial Guinea' },
  { id: 57, label: 'Eritrea' },
  { id: 58, label: 'Estonia' },
  { id: 59, label: 'Ethiopia' },
  { id: 60, label: 'Fiji' },
  { id: 61, label: 'Finland' },
  { id: 62, label: 'France' },
  { id: 63, label: 'Gabon' },
  { id: 64, label: 'Gambia' },
  { id: 65, label: 'Georgia' },
  { id: 66, label: 'Germany' },
  { id: 67, label: 'Ghana' },
  { id: 68, label: 'Greece' },
  { id: 69, label: 'Grenada' },
  { id: 70, label: 'Guatemala' },
  { id: 71, label: 'Guinea' },
  { id: 72, label: 'Guinea-Bissau' },
  { id: 73, label: 'Guyana' },
  { id: 74, label: 'Haiti' },
  { id: 75, label: 'Honduras' },
  { id: 76, label: 'Hungary' },
  { id: 77, label: 'Iceland' },
  { id: 78, label: 'India' },
  { id: 79, label: 'Indonesia' },
  { id: 80, label: 'Iran, Islamic Republic of' },
  { id: 81, label: 'Iraq' },
  { id: 82, label: 'Ireland' },
  { id: 83, label: 'Isle of Man' },
  { id: 84, label: 'Israel' },
  { id: 85, label: 'Italy' },
  { id: 86, label: 'Jamaica' },
  { id: 87, label: 'Japan' },
  { id: 88, label: 'Jersey' },
  { id: 89, label: 'Jordan' },
  { id: 90, label: 'Kazakhstan' },
  { id: 91, label: 'Kenya' },
  { id: 92, label: 'Kiribati' },
  { id: 93, label: 'Korea, Democratic People\'s Republic of' },
  { id: 94, label: 'Korea, Republic of' },
  { id: 95, label: 'Kuwait' },
  { id: 96, label: 'Kyrgyzstan' },
  { id: 97, label: 'Lao People\'s Democratic Republic' },
  { id: 98, label: 'Latvia' },
  { id: 99, label: 'Lebanon' },
  { id: 100, label: 'Lesotho' },
  { id: 101, label: 'Liberia' },
  { id: 102, label: 'Libya' },
  { id: 103, label: 'Liechtenstein' },
  { id: 104, label: 'Lithuania' },
  { id: 105, label: 'Luxembourg' },
  { id: 106, label: 'Macao' },
  { id: 107, label: 'Macedonia, the former Yugoslav Republic of' },
  { id: 108, label: 'Madagascar' },
  { id: 109, label: 'Malawi' },
  { id: 110, label: 'Malaysia' },
  { id: 111, label: 'Maldives' },
  { id: 112, label: 'Mali' },
  { id: 113, label: 'Malta' },
  { id: 114, label: 'Marshall Islands' },
  { id: 115, label: 'Mauritania' },
  { id: 116, label: 'Mauritius' },
  { id: 117, label: 'Mexico' },
  { id: 118, label: 'Micronesia, Federated States of' },
  { id: 119, label: 'Moldova, Republic of' },
  { id: 120, label: 'Monaco' },
  { id: 121, label: 'Mongolia' },
  { id: 122, label: 'Montenegro' },
  { id: 123, label: 'Morocco' },
  { id: 124, label: 'Mozambique' },
  { id: 125, label: 'Myanmar' },
  { id: 126, label: 'Namibia' },
  { id: 127, label: 'Nauru' },
  { id: 128, label: 'Nepal' },
  { id: 129, label: 'Netherlands' },
  { id: 130, label: 'New Caledonia' },
  { id: 131, label: 'New Zealand' },
  { id: 132, label: 'Nicaragua' },
  { id: 133, label: 'Niger' },
  { id: 134, label: 'Nigeria' },
  { id: 135, label: 'Niue' },
  { id: 136, label: 'Norfolk Island' },
  { id: 137, label: 'Northern Mariana Islands' },
  { id: 138, label: 'Norway' },
  { id: 139, label: 'Oman' },
  { id: 140, label: 'Pakistan' },
  { id: 141, label: 'Palau' },
  { id: 142, label: 'Palestine, State of' },
  { id: 143, label: 'Panama' },
  { id: 144, label: 'Papua New Guinea' },
  { id: 145, label: 'Paraguay' },
  { id: 146, label: 'Peru' },
  { id: 147, label: 'Philippines' },
  { id: 148, label: 'Pitcairn' },
  { id: 149, label: 'Poland' },
  { id: 150, label: 'Portugal' },
  { id: 151, label: 'Puerto Rico' },
  { id: 152, label: 'Qatar' },
  { id: 153, label: 'Réunion' },
  { id: 154, label: 'Romania' },
  { id: 155, label: 'Russian Federation' },
  { id: 156, label: 'Rwanda' },
  { id: 157, label: 'Saint Barthélemy' },
  { id: 158, label: 'Saint Helena, Ascension and Tristan da Cunha' },
  { id: 159, label: 'Saint Kitts and Nevis' },
  { id: 160, label: 'Saint Lucia' },
  { id: 161, label: 'Saint Martin (French part)' },
  { id: 162, label: 'Saint Pierre and Miquelon' },
  { id: 163, label: 'Saint Vincent and the Grenadines' },
  { id: 164, label: 'Samoa' },
  { id: 165, label: 'San Marino' },
  { id: 166, label: 'Sao Tome and Principe' },
  { id: 167, label: 'Saudi Arabia' },
  { id: 168, label: 'Senegal' },
  { id: 169, label: 'Serbia' },
  { id: 170, label: 'Seychelles' },
  { id: 171, label: 'Sierra Leone' },
  { id: 172, label: 'Singapore' },
  { id: 173, label: 'Sint Maarten (Dutch part)' },
  { id: 174, label: 'Slovakia' },
  { id: 175, label: 'Slovenia' },
  { id: 176, label: 'Solomon Islands' },
  { id: 177, label: 'Somalia' },
  { id: 178, label: 'South Africa' },
  { id: 179, label: 'South Georgia and the South Sandwich Islands' },
  { id: 180, label: 'South Sudan' },
  { id: 181, label: 'Spain' },
  { id: 182, label: 'Sri Lanka' },
  { id: 183, label: 'Sudan' },
  { id: 184, label: 'Suriname' },
  { id: 185, label: 'Svalbard and Jan Mayen' },
  { id: 186, label: 'Swaziland' },
  { id: 187, label: 'Sweden' },
  { id: 188, label: 'Switzerland' },
  { id: 189, label: 'Syrian Arab Republic' },
  { id: 190, label: 'Taiwan, Province of China' },
  { id: 191, label: 'Tajikistan' },
  { id: 192, label: 'Tanzania, United Republic of' },
  { id: 193, label: 'Thailand' },
  { id: 194, label: 'Timor-Leste' },
  { id: 195, label: 'Togo' },
  { id: 196, label: 'Tokelau' },
  { id: 197, label: 'Tonga' },
  { id: 198, label: 'Trinidad and Tobago' },
  { id: 199, label: 'Tunisia' },
  { id: 200, label: 'Turkey' },
  { id: 201, label: 'Turkmenistan' },
  { id: 202, label: 'Turks and Caicos Islands' },
  { id: 203, label: 'Tuvalu' },
  { id: 204, label: 'Uganda' },
  { id: 205, label: 'Ukraine' },
  { id: 206, label: 'United Arab Emirates' },
  { id: 207, label: 'United Kingdom' },
  { id: 208, label: 'United States' },
  { id: 209, label: 'Uruguay' },
  { id: 210, label: 'Uzbekistan' },
  { id: 211, label: 'Vanuatu' },
  { id: 212, label: 'Venezuela, Bolivarian Republic of' },
  { id: 213, label: 'Viet Nam' },
  { id: 214, label: 'Virgin Islands, British' },
  { id: 215, label: 'Virgin Islands, U.S.' },
  { id: 216, label: 'Wallis and Futuna' },
  { id: 217, label: 'Western Sahara' },
  { id: 218, label: 'Yemen' },
  { id: 219, label: 'Zambia' },
  { id: 220, label: 'Zimbabwe' }
];


export default countries;

  